### ISSUE TITLE
ceylon.formatter integration

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-dist#43]
If we add the plugin scripts from [`ceylon.formatter`](https://github.com/ceylon/ceylon.formatter/commit/226c14e6a6f768dccb4e80fc9a5cf9f96e6b9646) to the distribution, `ceylon format` should Just Work™ – the required modules should be downloaded from the Herd on first run.

**Comment by quintesse** [comment]
So, now how to integrate this in the distribution. I was thinking of a not-so-nice way where we just make a copy of the `.plugin` file in the (new) folder `ceylon-dist/bin` and make ant copy the contents of that to `ceylon-dist/dist/bin` during build. It works and would avoid having to make sure `ceylon.formatter` is available somewhere locally.

**Comment by quintesse** [comment]
Willing to pick this up yourself @lucaswerkmeister ? I'm not sure I'll have time tomorrow myself.

**Comment by lucaswerkmeister** [comment]
I probably won’t have time either, busy with uni stuff until up to 19:00 (perhaps earlier, but not sure).
