### ISSUE TITLE
upgrade to txtmark 0.13

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-dist#52]
We need to update txtmark across all projects.

**Comment by lucaswerkmeister** [comment]
CC ceylon/ceylon-herd#220

**Comment by gavinking** [comment]
@FroMage you're going to have to do this because you are the one who owns the module in Herd.

**Comment by FroMage** [comment]
Nope. I've just granted you permissions ;)

**Comment by FroMage** [comment]
Nice try, though.

**Comment by gavinking** [comment]
Oooh so smug, but that was a terrible tactic: you just forced me to report three new bugs. :-)

**Comment by FroMage** [comment]
Hey, feedback on it is good, so I stil win ;) And now you JUST have to fix these issues yourself ;)

**Comment by gavinking** [comment]
This is done.
