### ISSUE TITLE
update JBoss Modules and friends

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-dist#53]
- JBoss Modules is currently at 1.4.4.Final and we are using 1.3.3.Final
- JBoss logmanager is currently at 2.0.3.Final and we are using 1.4.0.Final
- JBoss Jandex is currently at 2.0.0.Final and we are using 1.0.3.Final

I think we should update these.

**Comment by FroMage** [comment]
I think it's a mistake to update any lib that has no bug fix we need explicitly, just before a release, which means before we can really test it. I think this update should wait for the beginning of 1.3.

**Comment by gavinking** [comment]
I have uploaded the new versions to Herd so they are there now and all we need to do is update the dist to make use of them.

**Comment by gavinking** [comment]
Done.
