### ISSUE TITLE
language module is missing links to source code

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-dist#60]
The ceylon doc for the language module 1.2 release has no links from the generated docs to the source code. What's weird about this is the source code is actually there, there just aren't any links to it.

This problem does not affect the SDK docs.

**Comment by FroMage** [comment]
It's in the build.xml of ceylon-dist, no?

**Comment by gavinking** [comment]
I'm not certain. I found something in the build of the language module.

**Comment by FroMage** [comment]
Yes but the build does not use it. Confusing, I know.

**Comment by gavinking** [comment]
@FroMage do you happen to know where it _is_ then, since it's not in `ceylon-dist/build.xml`.

**Comment by FroMage** [comment]
Errr, aside from this line:

```xml
    <target name="generate-apidoc">
```

;)

**Comment by gavinking** [comment]
you don't use the Ant task?!

**Comment by FroMage** [comment]
Why do you assume I wrote that thing?

**Comment by gavinking** [comment]
I just don't know why we would use `exec` when we have an Ant task for that.

That's why I didn't find it there.

Also, it actually does pass the `--source-code` argument, so I'm not sure why it's not working.

**Comment by gavinking** [comment]
I just did a build of the dist, and it seems that this is now fixed. Looks like the problem _was_ the `build.xml` for `ceylon.language`... closing.

**Comment by xkr47** [comment]
So.. will we have the source code available? Or do we wait for 1.2.1 / 1.3.0 ?
